// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 14);
lv_obj_set_width( ui_TabView1, 256);
lv_obj_set_height( ui_TabView1, 113);
lv_obj_clear_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_outline_color(ui_TabView1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_TabView1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_TabView1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_TabView1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TabView1, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_border_color(lv_tabview_get_tab_btns(ui_TabView1), lv_color_hex(0x686868),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(lv_tabview_get_tab_btns(ui_TabView1), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(lv_tabview_get_tab_btns(ui_TabView1), 1,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_TabView1), LV_BORDER_SIDE_FULL,  LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_TabPage0 = lv_tabview_add_tab(ui_TabView1, "Console");

ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Files");

ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Status");

ui_BtnF1 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_BtnF1, 40);
lv_obj_set_height( ui_BtnF1, 13);
lv_obj_set_x( ui_BtnF1, 0 );
lv_obj_set_y( ui_BtnF1, 114 );
lv_obj_add_flag( ui_BtnF1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnF1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnF1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnF1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BtnF1, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnF1, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF1Label = lv_label_create(ui_BtnF1);
lv_obj_set_width( ui_BtnF1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnF1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnF1Label, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_BtnF1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnF1Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF2 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_BtnF2, 40);
lv_obj_set_height( ui_BtnF2, 13);
lv_obj_set_x( ui_BtnF2, 43 );
lv_obj_set_y( ui_BtnF2, 114 );
lv_obj_add_flag( ui_BtnF2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnF2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnF2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnF2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BtnF2, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnF2, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF2Label = lv_label_create(ui_BtnF2);
lv_obj_set_width( ui_BtnF2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnF2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnF2Label, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_BtnF2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnF2Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF3 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_BtnF3, 40);
lv_obj_set_height( ui_BtnF3, 13);
lv_obj_set_x( ui_BtnF3, 86 );
lv_obj_set_y( ui_BtnF3, 114 );
lv_obj_add_flag( ui_BtnF3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnF3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnF3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnF3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BtnF3, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnF3, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF3Label = lv_label_create(ui_BtnF3);
lv_obj_set_width( ui_BtnF3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnF3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnF3Label, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_BtnF3Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnF3Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF4 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_BtnF4, 40);
lv_obj_set_height( ui_BtnF4, 13);
lv_obj_set_x( ui_BtnF4, 129 );
lv_obj_set_y( ui_BtnF4, 114 );
lv_obj_add_flag( ui_BtnF4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnF4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnF4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnF4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BtnF4, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnF4, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF4Label = lv_label_create(ui_BtnF4);
lv_obj_set_width( ui_BtnF4Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnF4Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnF4Label, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_BtnF4Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnF4Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF5 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_BtnF5, 40);
lv_obj_set_height( ui_BtnF5, 13);
lv_obj_set_x( ui_BtnF5, 172 );
lv_obj_set_y( ui_BtnF5, 114 );
lv_obj_add_flag( ui_BtnF5, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnF5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnF5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnF5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BtnF5, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnF5, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF5Label = lv_label_create(ui_BtnF5);
lv_obj_set_width( ui_BtnF5Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnF5Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnF5Label, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_BtnF5Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnF5Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF6 = lv_btn_create(ui_Screen1);
lv_obj_set_width( ui_BtnF6, 41);
lv_obj_set_height( ui_BtnF6, 13);
lv_obj_set_x( ui_BtnF6, 215 );
lv_obj_set_y( ui_BtnF6, 114 );
lv_obj_add_flag( ui_BtnF6, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BtnF6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BtnF6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BtnF6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_BtnF6, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BtnF6, &lv_font_montserrat_10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BtnF6Label = lv_label_create(ui_BtnF6);
lv_obj_set_width( ui_BtnF6Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BtnF6Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_BtnF6Label, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_BtnF6Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BtnF6Label, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}
