// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_TabView1;
lv_obj_t *ui_TabPage0;
lv_obj_t *ui_TabPage1;
lv_obj_t *ui_TabPage2;
lv_obj_t *ui_BtnF1;
lv_obj_t *ui_BtnF1Label;
lv_obj_t *ui_BtnF2;
lv_obj_t *ui_BtnF2Label;
lv_obj_t *ui_BtnF3;
lv_obj_t *ui_BtnF3Label;
lv_obj_t *ui_BtnF4;
lv_obj_t *ui_BtnF4Label;
lv_obj_t *ui_BtnF5;
lv_obj_t *ui_BtnF5Label;
lv_obj_t *ui_BtnF6;
lv_obj_t *ui_BtnF6Label;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 8
    #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_basic_init(dispp);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
