// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

   // #include "lv_i18n.h"
#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_TabPage0;
extern lv_obj_t *ui_TabPage1;
extern lv_obj_t *ui_TabPage2;
extern lv_obj_t *ui_BtnF1;
extern lv_obj_t *ui_BtnF1Label;
extern lv_obj_t *ui_BtnF2;
extern lv_obj_t *ui_BtnF2Label;
extern lv_obj_t *ui_BtnF3;
extern lv_obj_t *ui_BtnF3Label;
extern lv_obj_t *ui_BtnF4;
extern lv_obj_t *ui_BtnF4Label;
extern lv_obj_t *ui_BtnF5;
extern lv_obj_t *ui_BtnF5Label;
extern lv_obj_t *ui_BtnF6;
extern lv_obj_t *ui_BtnF6Label;
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
